export const TestData = {
  code: 1,
  result: [
    {
      tname: "Ram kumar",
      id: "291",
      is_assigned: "1",
      created: "2023-03-02",
      name: "Ram Prakash ltd..101",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-291",
      fact_case: "<p>ghjgjgjgh</p>",
      Exp_Delivery_Date: "2023-03-11",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "2",
      status: "Inprogress Query",
      statusdescription: null,
    },
    {
      tname: "Ram kumar",
      id: "248",
      is_assigned: "1",
      created: "2022-12-19",
      name: "Prateek",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-248",
      fact_case: "<p>query one</p>",
      Exp_Delivery_Date: "2022-12-31",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "6",
      status: "Declined Query",
      statusdescription: "Client Declined; Proposal",
    },
    {
      tname: "Ram kumar",
      id: "227",
      is_assigned: "1",
      created: "2022-11-28",
      name: "Testing",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-227",
      fact_case: "<p>upload folder testing</p>",
      Exp_Delivery_Date: "2022-12-09",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "2",
      status: "Inprogress Query",
      statusdescription: null,
    },
    {
      tname: "Ram kumar",
      id: "224",
      is_assigned: "1",
      created: "2022-11-28",
      name: "Testing",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-224",
      fact_case: "<p>testStaging</p>",
      Exp_Delivery_Date: "2022-12-11",
      client_discussion: "completed",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "200",
      is_assigned: "1",
      created: "2022-10-18",
      name: "Testing",
      cat_id: "5",
      cat_name: "Appeals",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-13-200",
      fact_case: "<p>fifth query</p>",
      Exp_Delivery_Date: "2022-10-30",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Declined Query",
      statusdescription: "Client Declined; Payment",
    },
    {
      tname: "Ram kumar",
      id: "192",
      is_assigned: "1",
      created: "2022-10-15",
      name: "Ram Prakash ltd..101",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-192",
      fact_case: "<p>addfresh query</p>",
      Exp_Delivery_Date: "2022-10-21",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "191",
      is_assigned: "1",
      created: "2022-10-15",
      name: "Ram Prakash ltd..101",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-191",
      fact_case: "<p>payment plan 1st</p>",
      Exp_Delivery_Date: "2022-10-21",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "190",
      is_assigned: "1",
      created: "2022-10-15",
      name: "Testing",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-190",
      fact_case: "<p>dfsfdfsdfsd</p>",
      Exp_Delivery_Date: "2022-10-31",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "2",
      status: "Inprogress Query",
      statusdescription: null,
    },
    {
      tname: "Ram kumar",
      id: "188",
      is_assigned: "1",
      created: "2022-10-13",
      name: "Testing",
      cat_id: "5",
      cat_name: "Appeals",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-13-188",
      fact_case: "<p>payment plan 3rd</p>",
      Exp_Delivery_Date: "2022-10-31",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "187",
      is_assigned: "1",
      created: "2022-10-13",
      name: "Testing",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-187",
      fact_case: "<p>payment plan 3rd</p>",
      Exp_Delivery_Date: "2022-10-28",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "186",
      is_assigned: "1",
      created: "2022-10-13",
      name: "Testing",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-186",
      fact_case: "<p>payment plan3</p>",
      Exp_Delivery_Date: "2022-10-31",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "184",
      is_assigned: "1",
      created: "2022-10-13",
      name: "Testing",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-184",
      fact_case: "<p>payment plan 1</p>",
      Exp_Delivery_Date: "2022-10-29",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "183",
      is_assigned: "1",
      created: "2022-10-10",
      name: "Testing",
      cat_id: "8",
      cat_name: "Others",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-16-183",
      fact_case: "<p>query 4th</p>",
      Exp_Delivery_Date: "2022-10-31",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "182",
      is_assigned: "1",
      created: "2022-10-10",
      name: "Testing",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-182",
      fact_case: "<p>query 3rd</p>",
      Exp_Delivery_Date: "2022-10-30",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "181",
      is_assigned: "1",
      created: "2022-10-10",
      name: "Testing",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-181",
      fact_case: "<p>query second</p>",
      Exp_Delivery_Date: "2022-10-30",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "2",
      status: "Inprogress Query",
      statusdescription: null,
    },
    {
      tname: "Ram kumar",
      id: "180",
      is_assigned: "1",
      created: "2022-10-10",
      name: "Testing",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-180",
      fact_case: "<p>query 1st</p>",
      Exp_Delivery_Date: "2022-10-30",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "4",
      status: "Inprogress Query",
      statusdescription: "Proposal",
    },
    {
      tname: "Ram kumar",
      id: "179",
      is_assigned: "1",
      created: "2022-10-05",
      name: "Testing",
      cat_id: "5",
      cat_name: "Appeals",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-13-179",
      fact_case: "<p>oljlkj</p>",
      Exp_Delivery_Date: "2022-10-30",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "178",
      is_assigned: "1",
      created: "2022-10-05",
      name: "Testing",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-178",
      fact_case: "<p>third</p>",
      Exp_Delivery_Date: "2022-10-27",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "177",
      is_assigned: "1",
      created: "2022-10-05",
      name: "Testing",
      cat_id: "4",
      cat_name: "Assessment",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-12-177",
      fact_case: "<p>second</p>",
      Exp_Delivery_Date: "2022-10-26",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "176",
      is_assigned: "1",
      created: "2022-10-05",
      name: "Testing",
      cat_id: "5",
      cat_name: "Appeals",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-13-176",
      fact_case: "<p>first</p>",
      Exp_Delivery_Date: "2022-10-28",
      client_discussion: "completed",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "169",
      is_assigned: "1",
      created: "2022-10-05",
      name: "Testing",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-169",
      fact_case: "<p>second</p>",
      Exp_Delivery_Date: "2022-10-13",
      client_discussion: "completed",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "168",
      is_assigned: "1",
      created: "2022-10-05",
      name: "Testing",
      cat_id: "5",
      cat_name: "Appeals",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-13-168",
      fact_case: "<p>query first</p>",
      Exp_Delivery_Date: "2022-10-20",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "165",
      is_assigned: "1",
      created: "2022-10-04",
      name: "Testing",
      cat_id: "5",
      cat_name: "Appeals",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-13-165",
      fact_case: "<p>LKUJHGDSF</p>",
      Exp_Delivery_Date: "2022-10-26",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "2",
      status: "Inprogress Query",
      statusdescription: null,
    },
    {
      tname: "Ram kumar",
      id: "32",
      is_assigned: "1",
      created: "2022-07-12",
      name: "Thales India Private Limited ",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-32",
      fact_case: "<p>Test Query 2</p>",
      Exp_Delivery_Date: "2022-07-29",
      client_discussion: "inprogress",
      draft_report: "inprogress",
      final_discussion: "inprogress",
      delivery_report: "inprogress",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "31",
      is_assigned: "1",
      created: "2022-07-12",
      name: "Thales India Private Limited ",
      cat_id: "3",
      cat_name: "Compliance",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-11-31",
      fact_case: "<p>Test Query 1</p>",
      Exp_Delivery_Date: "2022-07-28",
      client_discussion: "completed",
      draft_report: "completed",
      final_discussion: "completed",
      delivery_report: "completed",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "10",
      status: "Completed Query",
      statusdescription: "Assignment",
    },
    {
      tname: "Ram kumar",
      id: "22",
      is_assigned: "1",
      created: "2022-07-07",
      name: "Ram_test",
      cat_id: "5",
      cat_name: "Appeals",
      parent_id: "Direct tax",
      parent_id1: "",
      parent_id2: "",
      assign_no: "Q-13-22",
      fact_case: "<p>Direct tax test</p>",
      Exp_Delivery_Date: "2022-07-28",
      client_discussion: "completed",
      draft_report: "completed",
      final_discussion: "completed",
      delivery_report: "completed",
      reject: "0",
      accept: "1",
      tp_status: "2",
      status_code: "9",
      status: "Inprogress Query",
      statusdescription: "Assignment",
    },
  ],
};
